import { precacheAndRoute } from 'workbox-precaching';

// Precache all assets generated by Vite
precacheAndRoute((self as any).__WB_MANIFEST);

// Handle Push Notifications
self.addEventListener('push', (event: any) => {
    const data = event.data ? event.data.json() : { title: 'Nova Notificação', body: 'Você tem uma nova atualização no TRG Nexus.' };

    const options = {
        body: data.body,
        icon: '/logo.svg',
        badge: '/favicon.ico',
        data: data.data || {},
        actions: data.actions || [],
        vibrate: [100, 50, 100],
    };

    event.waitUntil(
        (self as any).registration.showNotification(data.title, options)
    );
});

// Handle Notification Clicks
self.addEventListener('notificationclick', (event: any) => {
    event.notification.close();

    const urlToOpen = event.notification.data?.url || '/';

    event.waitUntil(
        (self as any).clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients: any) => {
            // Check if there is already a window/tab open with the target URL
            for (let i = 0; i < windowClients.length; i++) {
                const client = windowClients[i];
                if (client.url === urlToOpen && 'focus' in client) {
                    return client.focus();
                }
            }
            // If not, open a new window/tab
            if ((self as any).clients.openWindow) {
                return (self as any).clients.openWindow(urlToOpen);
            }
        })
    );
});
