@echo off
echo Setting up Vercel Environment Variables...

echo Adding VITE_SUPABASE_URL...
echo https://xvojvmooybqfsfcmfped.supabase.co| npx vercel env add VITE_SUPABASE_URL production

echo Adding VITE_SUPABASE_ANON_KEY...
echo YOUR_ANON_KEY_HERE| npx vercel env add VITE_SUPABASE_ANON_KEY production

echo Adding SUPABASE_SERVICE_ROLE_KEY...
echo YOUR_SERVICE_ROLE_KEY_HERE| npx vercel env add SUPABASE_SERVICE_ROLE_KEY production

echo Adding SMTP_HOST...
echo smtp.gmail.com| npx vercel env add SMTP_HOST production

echo Adding SMTP_PORT...
echo 465| npx vercel env add SMTP_PORT production

echo Adding SMTP_USER...
echo pedrodiogo.suporte@gmail.com| npx vercel env add SMTP_USER production

echo Adding SMTP_PASS...
echo YOUR_SMTP_PASS_HERE| npx vercel env add SMTP_PASS production

echo Adding VITE_APP_URL...
echo https://trg-nexus-saas-klwkf1w4h-pedro-diogos-projects.vercel.app| npx vercel env add VITE_APP_URL production

echo Adding STRIPE_SECRET_KEY...
echo YOUR_STRIPE_SECRET_KEY| npx vercel env add STRIPE_SECRET_KEY production

echo Adding VITE_STRIPE_PUBLISHABLE_KEY...
echo YOUR_STRIPE_PUBLIC_KEY| npx vercel env add VITE_STRIPE_PUBLISHABLE_KEY production

echo Done!
